sonar.projectKey=invoice-creation-nodejs
sonar.qualitygate.wait=true
sonar.login=f652e869b3d8b3dc53a184bd9e63c7e74076b111
sonar.host.url=https://sonarqube.sa-labs.info
sonar.projectName=invoice-creation-nodejs
sonar.projectVersion=1.0
sonar.language=js
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=config/*,src/types/*,src/models/*.ts
sonar.coverage.exclusions=node_modules/*,coverage/lcov-report/*,config/*,src/model/*.ts
sonar.test.inclusions=src/**/*.spec.js,src/**/*.spec.jsx,src/**/*.test.js,src/**/*.test.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
